<?php

namespace App\Services;

use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Storage;

class ExportService
{
    /**
     * Export data to Excel format.
     * Note: For full Excel support with charts, install maatwebsite/excel package
     */
    public function exportToExcel(string $reportType, array $data, array $metadata): string
    {
        // For now, we'll create a CSV with .xlsx extension
        // To get true Excel with formatting and charts, install: composer require maatwebsite/excel
        $csv = $this->generateCsvContent($reportType, $data, $metadata);
        
        $filename = $this->generateFilename($reportType, 'xlsx');
        $path = storage_path('app/exports/' . $filename);
        
        // Ensure directory exists
        if (!file_exists(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }
        
        file_put_contents($path, $csv);
        
        return $path;
    }

    /**
     * Export data to CSV format.
     */
    public function exportToCsv(string $reportType, array $data, array $metadata): string
    {
        $csv = $this->generateCsvContent($reportType, $data, $metadata);
        
        $filename = $this->generateFilename($reportType, 'csv');
        $path = storage_path('app/exports/' . $filename);
        
        // Ensure directory exists
        if (!file_exists(dirname($path))) {
            mkdir(dirname($path), 0755, true);
        }
        
        file_put_contents($path, $csv);
        
        return $path;
    }

    /**
     * Generate CSV content based on report type.
     */
    protected function generateCsvContent(string $reportType, array $data, array $metadata): string
    {
        $csv = $this->generateMetadataHeader($metadata);
        
        $csv .= match($reportType) {
            'revenue_total' => $this->formatRevenueTotalCsv($data),
            'revenue_by_visa_type' => $this->formatRevenueBreakdownCsv($data, 'Visa Type'),
            'revenue_by_country' => $this->formatRevenueBreakdownCsv($data, 'Country'),
            'revenue_by_tier' => $this->formatRevenueBreakdownCsv($data, 'Processing Tier'),
            'revenue_trends' => $this->formatTrendsCsv($data, 'Revenue'),
            'visitors_by_country' => $this->formatVisitorsByCountryCsv($data),
            'approval_rates' => $this->formatApprovalRatesCsv($data),
            'visitor_trends' => $this->formatTrendsCsv($data, 'Applications'),
            'demographics' => $this->formatDemographicsCsv($data),
            'ai_query_result' => $this->formatAiQueryResultCsv($data),
            default => $this->formatGenericCsv($data),
        };
        
        return $csv;
    }

    /**
     * Generate metadata header for CSV.
     */
    protected function generateMetadataHeader(array $metadata): string
    {
        $csv = "# Ghana eVisa Analytics Report\n";
        $csv .= "# Generated: " . now()->format('Y-m-d H:i:s') . "\n";
        
        if (isset($metadata['admin_name'])) {
            $csv .= "# Generated by: {$metadata['admin_name']}\n";
        }
        
        if (isset($metadata['start_date']) && isset($metadata['end_date'])) {
            $csv .= "# Period: {$metadata['start_date']} to {$metadata['end_date']}\n";
        }
        
        if (isset($metadata['query'])) {
            $csv .= "# Query: {$metadata['query']}\n";
        }
        
        $csv .= "#\n\n";
        
        return $csv;
    }

    /**
     * Format revenue total CSV.
     */
    protected function formatRevenueTotalCsv(array $data): string
    {
        $csv = "Metric,Value\n";
        $csv .= "Total Revenue," . $this->formatCurrency($data['total'] ?? 0) . "\n";
        $csv .= "Currency,GHS\n";
        
        if (isset($data['period'])) {
            $csv .= "Period,{$data['period']}\n";
        }
        
        return $csv;
    }

    /**
     * Format revenue breakdown CSV.
     */
    protected function formatRevenueBreakdownCsv(array $data, string $categoryLabel): string
    {
        $csv = "{$categoryLabel},Payment Count,Total Revenue (GHS),Average Amount (GHS),Percentage\n";
        
        foreach ($data as $item) {
            $category = $item['visa_type'] ?? $item['country'] ?? $item['tier'] ?? 'Unknown';
            $count = $item['count'] ?? 0;
            $total = $this->formatCurrency($item['total'] ?? 0);
            $average = $this->formatCurrency($item['average'] ?? 0);
            $percentage = isset($item['percentage']) ? $this->formatPercentage($item['percentage']) : 'N/A';
            
            $csv .= "\"{$category}\",{$count},{$total},{$average},{$percentage}\n";
        }
        
        return $csv;
    }

    /**
     * Format trends CSV.
     */
    protected function formatTrendsCsv(array $data, string $metricLabel): string
    {
        $csv = "Period,{$metricLabel},Change %\n";
        
        foreach ($data as $item) {
            $period = $item['period'] ?? 'Unknown';
            $value = $item['total'] ?? $item['count'] ?? 0;
            $change = $item['change_percentage'] ?? 'N/A';
            
            $csv .= "{$period},{$value},{$change}\n";
        }
        
        return $csv;
    }

    /**
     * Format visitors by country CSV.
     */
    protected function formatVisitorsByCountryCsv(array $data): string
    {
        $csv = "Country,Application Count,Percentage\n";
        
        foreach ($data as $item) {
            $country = $item['country'] ?? 'Unknown';
            $count = $item['count'] ?? 0;
            $percentage = $this->formatPercentage($item['percentage'] ?? 0);
            
            $csv .= "\"{$country}\",{$count},{$percentage}\n";
        }
        
        return $csv;
    }

    /**
     * Format approval rates CSV.
     */
    protected function formatApprovalRatesCsv(array $data): string
    {
        $csv = "Country,Total Applications,Approved,Denied,Pending,Approval Rate,Denial Rate,Pending Rate\n";
        
        foreach ($data as $item) {
            $country = $item['country'] ?? 'Unknown';
            $total = $item['total'] ?? 0;
            $approved = $item['approved'] ?? 0;
            $denied = $item['denied'] ?? 0;
            $pending = $item['pending'] ?? 0;
            $approvalRate = $this->formatPercentage($item['approval_rate'] ?? 0);
            $denialRate = $this->formatPercentage($item['denial_rate'] ?? 0);
            $pendingRate = $this->formatPercentage($item['pending_rate'] ?? 0);
            
            $csv .= "\"{$country}\",{$total},{$approved},{$denied},{$pending},{$approvalRate},{$denialRate},{$pendingRate}\n";
        }
        
        return $csv;
    }

    /**
     * Format demographics CSV.
     */
    protected function formatDemographicsCsv(array $data): string
    {
        $csv = "# Age Groups\n";
        $csv .= "Age Group,Count,Percentage\n";
        
        foreach ($data['age_groups'] ?? [] as $group => $stats) {
            $csv .= "{$group},{$stats['count']},{$this->formatPercentage($stats['percentage'])}\n";
        }
        
        $csv .= "\n# Gender Distribution\n";
        $csv .= "Gender,Count,Percentage\n";
        
        foreach ($data['gender'] ?? [] as $gender => $stats) {
            $csv .= ucfirst($gender) . ",{$stats['count']},{$this->formatPercentage($stats['percentage'])}\n";
        }
        
        $csv .= "\n# Purpose of Visit\n";
        $csv .= "Purpose,Count,Percentage\n";
        
        foreach ($data['purpose_of_visit'] ?? [] as $purpose => $stats) {
            $csv .= "\"{$purpose}\",{$stats['count']},{$this->formatPercentage($stats['percentage'])}\n";
        }
        
        return $csv;
    }

    /**
     * Format AI query result CSV.
     */
    protected function formatAiQueryResultCsv(array $data): string
    {
        if (empty($data)) {
            return "No data available\n";
        }
        
        // If data is a simple array of objects, format as table
        if (isset($data[0]) && is_array($data[0])) {
            $headers = array_keys($data[0]);
            $csv = implode(',', $headers) . "\n";
            
            foreach ($data as $row) {
                $values = array_map(function ($value) {
                    if (is_string($value) && (strpos($value, ',') !== false || strpos($value, '"') !== false)) {
                        return '"' . str_replace('"', '""', $value) . '"';
                    }
                    return $value;
                }, array_values($row));
                
                $csv .= implode(',', $values) . "\n";
            }
            
            return $csv;
        }
        
        // Otherwise, format as key-value pairs
        return $this->formatGenericCsv($data);
    }

    /**
     * Format generic data as CSV.
     */
    protected function formatGenericCsv(array $data): string
    {
        $csv = "Key,Value\n";
        
        foreach ($data as $key => $value) {
            if (is_array($value)) {
                $value = json_encode($value);
            }
            
            $csv .= "\"{$key}\",\"{$value}\"\n";
        }
        
        return $csv;
    }

    /**
     * Format currency value.
     */
    public function formatCurrency(float $amount): string
    {
        return number_format($amount, 2, '.', '');
    }

    /**
     * Format percentage value.
     */
    public function formatPercentage(float $value): string
    {
        return number_format($value, 1, '.', '') . '%';
    }

    /**
     * Format date in ISO 8601 format.
     */
    public function formatDate(\DateTime $date): string
    {
        return $date->format('Y-m-d');
    }

    /**
     * Generate filename for export.
     */
    protected function generateFilename(string $reportType, string $extension): string
    {
        $timestamp = now()->format('Y-m-d_His');
        $sanitizedType = str_replace(' ', '_', strtolower($reportType));
        
        return "analytics_{$sanitizedType}_{$timestamp}.{$extension}";
    }
}
